//------------------------------------------------------------------------------
// <auto-generated>
//     이 코드는 도구를 사용하여 생성되었습니다.
//     런타임 버전:4.0.30319.42000
//
//     파일 내용을 변경하면 잘못된 동작이 발생할 수 있으며, 코드를 다시 생성하면
//     이러한 변경 내용이 손실됩니다.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wpf_study1.Properties {
    using System;
    
    
    /// <summary>
    ///   지역화된 문자열 등을 찾기 위한 강력한 형식의 리소스 클래스입니다.
    /// </summary>
    // 이 클래스는 ResGen 또는 Visual Studio와 같은 도구를 통해 StronglyTypedResourceBuilder
    // 클래스에서 자동으로 생성되었습니다.
    // 멤버를 추가하거나 제거하려면 .ResX 파일을 편집한 다음 /str 옵션을 사용하여 ResGen을
    // 다시 실행하거나 VS 프로젝트를 다시 빌드하십시오.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   이 클래스에서 사용하는 캐시된 ResourceManager 인스턴스를 반환합니다.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Wpf_study1.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   이 강력한 형식의 리소스 클래스를 사용하여 모든 리소스 조회에 대한 현재 스레드의 CurrentUICulture
        ///   속성을 재정의합니다.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Back과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Btn_Back {
            get {
                return ResourceManager.GetString("Btn_Back", resourceCulture);
            }
        }
        
        /// <summary>
        ///   C과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Btn_C {
            get {
                return ResourceManager.GetString("Btn_C", resourceCulture);
            }
        }
        
        /// <summary>
        ///   CE과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Btn_CE {
            get {
                return ResourceManager.GetString("Btn_CE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   .과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Btn_Point {
            get {
                return ResourceManager.GetString("Btn_Point", resourceCulture);
            }
        }
        
        /// <summary>
        ///   8과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Num_Eight {
            get {
                return ResourceManager.GetString("Num_Eight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   5과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Num_Five {
            get {
                return ResourceManager.GetString("Num_Five", resourceCulture);
            }
        }
        
        /// <summary>
        ///   4과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Num_Four {
            get {
                return ResourceManager.GetString("Num_Four", resourceCulture);
            }
        }
        
        /// <summary>
        ///   9과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Num_Nine {
            get {
                return ResourceManager.GetString("Num_Nine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   1과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Num_One {
            get {
                return ResourceManager.GetString("Num_One", resourceCulture);
            }
        }
        
        /// <summary>
        ///   7과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Num_Seven {
            get {
                return ResourceManager.GetString("Num_Seven", resourceCulture);
            }
        }
        
        /// <summary>
        ///   6과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Num_Six {
            get {
                return ResourceManager.GetString("Num_Six", resourceCulture);
            }
        }
        
        /// <summary>
        ///   3과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Num_Three {
            get {
                return ResourceManager.GetString("Num_Three", resourceCulture);
            }
        }
        
        /// <summary>
        ///   2과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Num_Two {
            get {
                return ResourceManager.GetString("Num_Two", resourceCulture);
            }
        }
        
        /// <summary>
        ///   0과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Num_Zero {
            get {
                return ResourceManager.GetString("Num_Zero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ÷과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Op_Divide {
            get {
                return ResourceManager.GetString("Op_Divide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   =과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Op_Equal {
            get {
                return ResourceManager.GetString("Op_Equal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ×과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Op_Multiply {
            get {
                return ResourceManager.GetString("Op_Multiply", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ±과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Op_PlusMinus {
            get {
                return ResourceManager.GetString("Op_PlusMinus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   -과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Op_Subtract {
            get {
                return ResourceManager.GetString("Op_Subtract", resourceCulture);
            }
        }
        
        /// <summary>
        ///   +과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Op_Sum {
            get {
                return ResourceManager.GetString("Op_Sum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   MyCalculator과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
    }
}
